import { Nav } from "@components/Nav";
import { Provider } from "@components/Provider";
import "@styles/globals.css";

// static metadata 
export const metadata = {
  title: "promptopia",
  description: "Generated by AI",
  
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image" href="/public/assets/images/logo.svg" />
      </head>
      <body>
        <Provider>
          <div className="main">
            <div className="gradient" />
          </div>
          <main className="app">
            <Nav />
            {children}
          </main>
        </Provider>
      </body>
    </html>
  );
}
